site_name: FortiDragon Documentation
site_description: Network Security Logs Analytics
site_author: Dragon
site_url: https://enotspe.github.io/fortinet-2-elasticsearch/

repo_name: enotspe/fortinet-2-elasticsearch
repo_url: https://github.com/enotspe/fortinet-2-elasticsearch
edit_uri: edit/main/docs/

theme:
  name: material
  icon:
    logo: fontawesome/solid/dragon

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    #- navigation.tabs
    #- navigation.tabs.sticky
    #- navigation.sections
    - navigation.expand
    - navigation.path
    #- navigation.prune
    - navigation.top
    - navigation.footer
    - navigation.indexes
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy
    - content.code.annotate
    #- content.action.edit  # Add edit button
    #- content.action.view  # Add view source button
    - toc.follow
    #- toc.integrate  # Integrates TOC into left sidebar

plugins:
  - search
  #    separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  - minify:
      minify_html: true
  # Consider adding:
  # - tags  # If you want to add tags to pages
  - awesome-pages # For easier nav organization
  - social
  - glightbox:
      #touchNavigation: true
      loop: true
      #effect: zoom
      #slide_effect: slide
      #width: 100%
      #height: auto
      #zoomable: true
      #draggable: true
      #skip_classes:
      #  - custom-skip-class-name
      #auto_themed: false
      #auto_caption: false
      #caption_position: bottom
      #background: white
      #shadow: true
      #manual: false

markdown_extensions:
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.blocks.caption
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.keys # For keyboard shortcuts
  - pymdownx.mark # For highlighting text
  - pymdownx.critic # For showing changes
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true
      permalink_title: Link to this section
  - footnotes
  - def_list

#nav:
#  - Home: index.md
#  - Engage: engage.md
#  - Architecture: architecture.md
#  - Roadmap: roadmap.md
#  - Installation:
#    - installation/index.md
#    - Datasource:
#     - Fortigate: installation/datasource/fortigate.md
#    - Ingest:
#     - Vector: installation/ingest/vector.md
#     - Elastic Agent: installation/ingest/elastic-agent.md
#     - Logstash: installation/ingest/logstash.md
#    - Storage:
#     - Victoria Logs: installation/storage/victoria.md
#     - Elasticsearch: installation/storage/elasticsearch.md
#    - Visualization:
#     - Grafana: installation/viz/grafana.md
#     - Kibana: installation/viz/kibana.md
#  - Dashboards:
#    - dashboards/index.md
#    - Canvas: dashboards/canvas.md
#    - Values: dashboards/values.md
#    - Datasets: dashboards/datasets.md
#    - Usage: dashboards/usage.md

extra:
  #generator: false # Hide "Made with Material for MkDocs" notice on the footer
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/enotspe/fortinet-2-elasticsearch
    - icon: fontawesome/brands/discord
      link: https://discord.gg/9qn4enV
  version:
    provider: mike # Optional: for versioning
#  consent:
#    title: Cookie consent
#    description: >-
#      We use cookies to recognize your repeated visits and preferences, as well
#      as to measure the effectiveness of our documentation and whether users
#      find what they're searching for. With your consent, you're helping us to
#      make our documentation better.
