site_name: FortiDragon Documentation
site_description: Network security logs analytics
site_author: Dragon
site_url: https://enotspe.github.io/fortinet-2-elasticsearch/

repo_name: enotspe/fortinet-2-elasticsearch
repo_url: https://github.com/enotspe/fortinet-2-elasticsearch
edit_uri: edit/main/docs/

theme:
  name: material
  palette:

    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    #- navigation.tabs
    #- navigation.tabs.sticky
    #- navigation.sections
    - navigation.expand
    - navigation.path
    #- navigation.prune
    - navigation.top
    - navigation.indexes
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy
    - content.code.annotate
    #- content.action.edit  # Add edit button
    #- content.action.view  # Add view source button
    - toc.follow
    #- toc.integrate  # Integrates TOC into left sidebar

plugins:
  - search
  #    separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  # TODO: Install these plugins in GitHub Actions
  # - git-revision-date-localized:
  #     enable_creation_date: true
  #     type: timeago
  # - minify:
  #     minify_html: true
  # Consider adding:
  # - tags  # If you want to add tags to pages
  - awesome-pages  # For easier nav organization
  - glightbox


markdown_extensions:
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.blocks.caption
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.keys  # For keyboard shortcuts
  - pymdownx.mark  # For highlighting text
  - pymdownx.critic  # For showing changes
  - admonition
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true
      permalink_title: Link to this section
  - footnotes
  - def_list
  #- glightbox
  - pymdownx.tasklist:
      custom_checkbox: true

#nav:
#  - Home: index.md
#  - Engage: engage.md
#  - Architecture: architecture.md
#  - Roadmap: roadmap.md
#  - Installation:
#    - installation/index.md
#    - Datasource: 
#     - Fortigate: installation/datasource/fortigate.md
#    - Ingest: 
#     - Vector: installation/ingest/vector.md
#     - Elastic Agent: installation/ingest/elastic-agent.md
#     - Logstash: installation/ingest/logstash.md
#    - Storage: 
#     - Victoria Logs: installation/storage/victoria.md
#     - Elasticsearch: installation/storage/elasticsearch.md
#    - Visualization: 
#     - Grafana: installation/viz/grafana.md
#     - Kibana: installation/viz/kibana.md
#  - Dashboards:
#    - dashboards/index.md
#    - Canvas: dashboards/canvas.md
#    - Values: dashboards/values.md
#    - Datasets: dashboards/datasets.md
#    - Usage: dashboards/usage.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/enotspe/fortinet-2-elasticsearch
  version:
    provider: mike  # Optional: for versioning
